Feature adi ndev 1061
bypasslane/angular-material-expander pull request #1
Opened 2017-01-12 21:11 UTC by AdiedX

## JIRA
https://bypassmobile.atlassian.net/browse/NDEV-1061

## Description
Fix navigation flickering issue when switching between sub tabs

2017-01-12 21:25 UTC, sdrioux commented on src/js/expanderExpanded.js
> +    var isAnimatedOpen = false;
1. Where does this ever get set to true?
2.  Did we not break any tests?

2017-01-12 21:48 UTC, B-3PO commented on src/js/expanderExpanded.js
> +    var isAnimatedOpen = false;
@sdrioux I never wrote tests for this ui component since it was so simple

2017-01-12 21:49 UTC, AdiedX commented on src/js/expanderExpanded.js
> +    var isAnimatedOpen = false;
Updated the PR.

2017-01-13 16:28 UTC, B-3PO commented
🚢

2017-01-13 17:16 UTC, JonathanTech requested changes

2017-01-13 17:16 UTC, JonathanTech commented on package.json
> +    "gulp-angular-templatecache": "^2.0.0",
This was added without anything being added to gulp. Please revert.

2017-01-13 17:16 UTC, JonathanTech commented on src/js/expanderExpanded.js
> +    var isAnimatedOpen = false;
Let's add tests for this. If it's a simple ui component, then the tests should be easy to write (relatively)

2017-01-13 17:16 UTC, JonathanTech commented on src/js/expanderExpanded.js
> +        if (isHeightSet === true) {
I really don't see the point of type checking this value. the value will be a bool as defined above

2017-01-13 17:17 UTC, JonathanTech commented
Sorry, there should be tests covering this. Let's get those in :)

2017-01-14 01:17 UTC, B-3PO commented on package.json
> +    "gulp-angular-templatecache": "^2.0.0",
This change is correct, i forgot to add it when i first built the component
https://github.com/bypasslane/angular-material-expander/blob/95efed78c059bb0bd66a5bdbc8c035ff3cbebcb8/gulpfile.js#L13

2017-01-14 01:20 UTC, B-3PO commented on src/js/expanderExpanded.js
> +        if (isHeightSet === true) {
Personally i like to add the true/false so anyone else reading the code can easily see the type, either way is correct.

2017-01-14 01:22 UTC, B-3PO commented
@JonathanTech FYI, i am responding these comments because most of the code was written by me

2017-01-14 01:49 UTC, JonathanTech commented on package.json
> +    "gulp-angular-templatecache": "^2.0.0",
ok, :)

2017-01-14 01:50 UTC, JonathanTech commented on src/js/expanderExpanded.js
> +        if (isHeightSet === true) {
To me it communicates that the type might be unknown or there's a possibility of it being not a bool. Personal preferences. Not a show stopper.

2017-01-17 17:12 UTC, txssseal commented on src/js/expanderExpanded.js
> +        if (isHeightSet === true) {
ya I agree with @JonathanTech.  If we want to do a type check lets wrap it in something like this?

```
if (typeof (variable) === "boolean") {

}
```

2017-01-17 20:56 UTC, JonathanTech commented
![image](https://cloud.githubusercontent.com/assets/1794139/22039473/12d5ad58-dcc5-11e6-992b-e18e4913c718.png)
:ship:

2017-01-17 20:56 UTC, JonathanTech approved these changes

2017-01-17 20:56 UTC, JonathanTech commented
@B-3PO Could you add me as admin on this project so I can add circle ci?

2017-01-17 21:20 UTC, merged